### ISSUE TITLE
html page not working

### ISSUE THREAD

**Issue by nikisalli** [ayushsharma82/WebSerial#1]
it always gives http error 500 (internal server error) 

libraries and cores used:
ESP32-arduino 1.0.1 (core)

ESPAsiyncWebServer direct download from here: https://github.com/me-no-dev/ESPAsyncWebServer

AsyncTCP direct download from here https://github.com/me-no-dev/AsyncTCP

am i using the wrong libraries?

**Comment by ayushsharma82** [comment]
WebSerial is accessible at "<IP Address>/webserial" url. Going to IP Address only will give you a 500 Error.

**Comment by nikisalli** [comment]
ok now it works, thanks!
