### ISSUE TITLE
Modify eeprom html?

### ISSUE THREAD

**Issue by eried** [ayushsharma82/WebSerial#18]
how do you generate the new eeprom html contents? (I want to add some custom serial commands)

everything is very clean looking btw :)

**Comment by omar117** [comment]
Para modificar este proyecto tienes que trabajar con vue.js, el autor creo un script que automáticamente te crea el archivo .h que necesitas sustituir en la librería para que puedas ver el resultado en su esp

**Comment by eried** [comment]
Gracias! Me di cuenta luego de revisarlo un rato :)
