### ISSUE TITLE
OTA fails if WebSerial WebPage is active

### ISSUE THREAD

**Issue by cph25** [ayushsharma82/WebSerial#21]
Thanks for providing the WebSerial solution!
The issue is OTA fails if a WebSerial webpage is open.
Maybe a WebSerial.stop() functionality which closes the WebUI would be sufficient.
Thanks
CPH

**Comment by ayushsharma82** [comment]
This doesn't provide me with any context to give a decision.
1) Which OTA library are you using?
2) Are you mixing Webserver with Asyncwebserver? These don't go along very well.

You may reopen this issue if you are still facing this problem.
