### ISSUE TITLE
Checking if there is room for more serial characters to avoid error too many messages qued

### ISSUE THREAD

**Issue by StefanL38** [ayushsharma82/WebSerial#25]
Hi,

is there a way to check if the WebSerial.println  or WebSerialPro.println  still has room for buffering more characters?

best regards Stefan

**Comment by ayushsharma82** [comment]
@StefanL38 This is directly linked to AsyncWebServer's WebSocket buffer. If you can increase it then it will increase the buffer of webserial as well.

**Comment by pancanet** [comment]
@StefanL38 you can try to change WS_MAX_QUEUED_MESSAGES value inside AsyncWebSocket.h,  the default value from library is 8 for esp8266 and 32 for esp32 and max value is 256. also, dont push data with webserial.print or .println too often, the library need a time to remove the buffer. 
![image](https://user-images.githubusercontent.com/63144021/136650017-aaf461f5-fc88-42e7-a326-edb4d4fc4780.png)

**Comment by ayushsharma82** [comment]
Solution provided by @pancanet. Closing.
