### ISSUE TITLE
Send message via URL

### ISSUE THREAD

**Issue by galtamur** [ayushsharma82/WebSerial#32]
Hello, I would like to send a message to the ESP32 by composing a URL, like <ip_address>/webserial/message=<my_message>
Is it possible anyhow?
Thank you,
GA

**Comment by ayushsharma82** [comment]
@galtamur  You can use DDNS and port forwarding to make your ESP publically available.

**Comment by ayushsharma82** [comment]
Oh sorry, I didn't read your message carefully the first time.

No, it's not possible to send a message via a query in URL.

**Comment by rkuo2000** [comment]
> Hello, I would like to send a message to the ESP32 by composing a URL, like <ip_address>/webserial/message=<my_message>
> Is it possible anyhow?
> Thank you,
> GA

You can <ip_address>/get?message="your_message"

Python sample codes: 
[sendHTTPget.py](https://github.com/rkuo2000/homebot/blob/master/sendHTTPget.py)
[sendHTTPpost.py](https://github.com/rkuo2000/homebot/blob/master/sendHTTPpost.py)
