### ISSUE TITLE
Resize the WebSerial Window on Mobile device? (Like on a desktop)

### ISSUE THREAD

**Issue by dannyz2** [ayushsharma82/WebSerial#39]
Hey, is it possible to resize the Serial window longer than 8 lines. I can see in the code where it is limited to 8 lines, but am uncertain how to go about re-compiling. On a desktop machine, I can simply re-size the window by dragging the lower right corner. I can see no way to do this on my mobile device? (The serial display uses less than 1/3 of my device screen, it would be nice to use more of my display.) Might it be possible to add a variable to the webserial_webpage.h file (or, the WebSerial.cpp), to allow the user to set the number of window lines? (Make it a Pro feature, & I would certainly donate for the Pro Version, as, I believe would a lot of others.)

**Comment by ayushsharma82** [comment]
You can resize on a mobile screen. The resize handler might be too small to grab which is a browser thing. Try grabbing the bottom right corner of webserial console.

I'll try to implement the window lines feature in my free time. Thanks for the suggestion.

**Comment by dannyz2** [comment]
Hello, thanks for your response. I have tried the bottom right corner as well, I cannot make it work. When I load the WebSerial webpage on a desktop PC, I can clearly see the handle to resize the window. When I load the same on a mobile device, no matter how much I zoom in, I cannot see a handle, & cannot seem to grab on to the correct spot to facilitate the resize.

**Comment by ayushsharma82** [comment]
@dannyz2  Thanks for testing! I'll look into it.

**Comment by swilson86** [comment]
I agree with dannyz2, I cannot change the window size on an iphone either. But another associated bug seems to exist... My iphone shuts off the screen after 30 seconds. When it wakes up the WebSerial window is empty.
