### ISSUE TITLE
Suggestion: Browserbased timestamps

### ISSUE THREAD

**Issue by zetadotbar0** [ayushsharma82/WebSerial#40]
I would like to suggest adding browserbased timestamps for each newline. This would be very usefull in some cases without the need do add it manually to every line via additional Webserial.print command.

**Comment by ayushsharma82** [comment]
Great suggestion! I'll try to implement it in my free time.

**Comment by ayushsharma82** [comment]
Finally I've been able to add this feature but in Pro version to justify the time spent. I feel obliged to give you a free copy of WebSerial Pro. Send me a mail at asrocks5@gmail.com to claim it :)

Regards,
Ayush
