### ISSUE TITLE
Use with Wifimanager

### ISSUE THREAD

**Issue by gfucka** [ayushsharma82/WebSerial#42]
If I try to use the library with Wifimanager I get error:
previous declaration 'httpmethod http_any' enum httpmethod { http_any, http_get, http_head, http_post, http_put, http_patch, http_delete, http_options };

There is a way to use it with Wifimanager?

**Comment by noize007** [comment]
You can use the AsyncWifiManager library instead of the usual WifiManager lib.

**Comment by ayushsharma82** [comment]
Solved by @noize007 . Closing this issue.
