### ISSUE TITLE
feature request: add new class method onConnect()

### ISSUE THREAD

**Issue by dstroy0** [ayushsharma82/WebSerial#44]
request a new method "onConnect()" that can accept a char * or const char * which will output a c-string or string literal when users connect to /webserial

**Comment by T-vK** [comment]
Hi, I'm requesting to re-open this issue. I'm looking for the exact same functionality or at least a workaround for now.
We basically need to know when the client is ready to receive messages which should be the same as soon as it has connected (or reconnected to the WebSocket at `/wserial`).

Looking at the source code, it should be as simple as adding a callback-call in here:

```
...
_ws->onEvent([&](__unused AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, __unused void * arg, uint8_t *data, __unused size_t len) -> void {
  ...
  if (type == WS_EVT_CONNECT) {
    // CALL CONNECT CALLBACK HERE
    ...
  }
...
```
