### ISSUE TITLE
WebSerial Ui

### ISSUE THREAD

**Issue by ra1n08** [ayushsharma82/WebSerial#46]
i want to edit Webpage for WebSerial
and i found this

[https://github.com/ayushsharma82/WebSerial/blob/master/src/webserial_webpage.h](url)

What is the sequence of numbers in const uint8_t WEBSERIAL_HTML[] PROGMEM for?

**Comment by Myjestic** [comment]
It is the whole html source , css and js as gzipped byte code.
But unfortunately the it is all obfuscated, so you cannot make any changes to layout or function.
