### ISSUE TITLE
Interface for webserial on port 2 / 3 at ESP32

### ISSUE THREAD

**Issue by PfeifferP** [ayushsharma82/WebSerial#52]
how is it possible to change the serial interface to port2 or 3 at ESP32. Keyword hardware serial

**Comment by PfeifferP** [comment]
please change title in "Interface for webserial on port 2 / 3 at ESP32"

**Comment by ayushsharma82** [comment]
Hi @PfeifferP ,

WebSerial does not attach itself to any hardware serial port. Incoming messages and out going messages can be configured according to the user. Modify this function to suite your needs: https://github.com/ayushsharma82/WebSerial/blob/master/examples/Demo/Demo.ino#L28

You can write a logic to attach both WebSerial and Hardware Serial together.
