### ISSUE TITLE
webserial_webpage.h details

### ISSUE THREAD

**Issue by CoolJavelin** [ayushsharma82/WebSerial#58]
I want to change the way the webserial webpage looks. I'd like a more efficient layout (less margins on top, bottom and sides.) Also, while the word at the top "Webserial" and its logo are cool, I'd like them to be much smaller.

Can you publish the source code that created the webserial_webpage.h?

Thanks, Mark.

**Comment by asjdf** [comment]
I thought he already published the frontend in [/ui](https://github.com/ayushsharma82/WebSerial/tree/master/ui)
