### ISSUE TITLE
WebSerial crashed because run out of memory 

### ISSUE THREAD

**Issue by romanbr2** [ayushsharma82/WebSerial#61]
I think you must count the lines, if you add a line to 'textArea.value' and after 200 Lines or so you must delete lines from the beginning.

**Comment by ayushsharma82** [comment]
Hi, Please report issues related to Pro editions via mail to support@softt.io only.

As resolving these issues can include snippets of exclusive code which are not to be released in public.

I've taken note of your suggestion and removed it from issue.
