### ISSUE TITLE
Timing Issue - Need delay between multiple WebSerial.println commands

### ISSUE THREAD

**Issue by JMWilton** [ayushsharma82/WebSerial#65]
When executing the following code:
WebSerial.println(WiFi.localIP());
 //delay(500);
 WebSerial.println("joe was here");
 // delay(500);
 WebSerial.println("this is now");

The output is:
![image](https://github.com/ayushsharma82/WebSerial/assets/56261911/7af8264f-f203-4ff7-8aec-c10bc0172554)

When executing the following code:
WebSerial.println(WiFi.localIP());
delay(500);
WebSerial.println("joe was here");
delay(500);
WebSerial.println("this is now");

The output is:
![image](https://github.com/ayushsharma82/WebSerial/assets/56261911/329b6fcd-6875-4be1-b3b2-9843439570e8)

It appears that subsequent WebSerial.println commands overwrite the previous WebSerial.println command if there is an insufficient delay.  It would be expected that no delay should be necessary.

**Comment by JMWilton** [comment]
I now suspect that the html receive event code might be reentered before it finishes its work.

**Comment by asjdf** [comment]
I thought this issue might be help

https://github.com/asjdf/WebSerialLite/issues/4#issuecomment-1342696623
