### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mattronix** [ayushsharma82/WebSerial#66]
Any tips on how i could implement basic auth?

**Comment by tinkering4fun** [comment]
Very late answer, but I get aware of this lib just a few days ago, and felt a need for enhancements in my project.

See my fork https://github.com/tinkering4fun/WebSerial-Custom-HTML and the new example Demo_Console.
By reading this issue, I recognized it as good idea and implemented it. :-)

The trick are new parameters in the begin() method.
If you just require auth, this should work.

`WebSerial.begin(&server, "/webserial", "user", "password");` 

If you strive for modifications of the UI, see the new example Demo_Console for what my fork was intended for.
See also my comments in issue #70.
