### ISSUE TITLE
WebSerial / Async support for Arduino V3.x

### ISSUE THREAD

**Issue by PureTek-Innovations** [ayushsharma82/WebSerial#72]
I have an ESP32S3 with a W5500 ethernet module, I can only get this to work with Arduino V3.0.0.0 alpha3.
I can't get the async libraries to compile with V3.x and wondered if you could help?
Thanks

**Comment by ayushsharma82** [comment]
@PureTek-Innovations  WebSerial has been updated to v2 which supports arduino-esp32 core v3.
