### ISSUE TITLE
[v2] Too many ping-pong messages

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/WebSerial#77]
The UI is sending to many ping requests, which forces the server to answer and then take a slot in the message queue.

![image](https://github.com/ayushsharma82/WebSerial/assets/61346/bcc440e9-53bd-4fe2-980d-9cef4caec958)

I message each 500ms / 1 sec would be largely enough, and the ping message should be sent **ONLY IF the UI did not receive a message recently.** Any message reception acts like a PONG...

**Comment by ayushsharma82** [comment]
A bug. It should have been same as 3 sec as `pro` version. Easy fix though.

**Comment by ayushsharma82** [comment]
Fixed as of `v2.0.1`
