### ISSUE TITLE
function onMessage dont works

### ISSUE THREAD

**Issue by tobiasfaust** [ayushsharma82/WebSerial#97]
Hi,
I tried your example Logging.ino as my first test with webserial. But it seems, the funktion onMessage dont works because i dont get the messages as real serial output. Output as webserial works. 
Do you imagine whats wrong? If web connection fails, i need the serial output as real serial output twice ;)

`WebSerial.onMessage([](const String& msg) { Serial.println(msg); });`

**Comment by tobiasfaust** [comment]
Hi @ayushsharma82
it would be fine if you could take a look into this?

**Comment by ayushsharma82** [comment]
@tobiasfaust I tested logging.ino example on my end and it still works. Message sent from WebSerial is begin printed in `Serial`. Please check your setup.

**Comment by tobiasfaust** [comment]
Hi @ayushsharma82 ,
thanks for your reply. 
For a real testcase close to your test 
1. i cloned your repo, 
2. correct a spelling mistake in platformio.ini
  mathieucarbou/ESP Async WebServer@^3.1.1 -> mathieucarbou/ESPAsyncWebServer@^3.1.1
3. compile for esp8266
4. upload, show serial monitor and webserial

and unfortunally, no change. perfect loggin in webserial, the last serial log shows me the first ip-Adress and no more

whats wrong? I havent further ideas...

![webserial](https://github.com/user-attachments/assets/f1a25b86-5706-4af8-aef3-a27cb18d2277)

**Comment by ayushsharma82** [comment]
Okay, so I tested it on ESP32. There must be an issue with ESP8266 part of code. I’ll check that when I’ll get some time in my hands.

@mathieucarbou You wrote this callback, have any idea why it’s not working?

**Comment by mathieucarbou** [comment]
@ayushsharma82 : it was fixed in https://github.com/ayushsharma82/WebSerial/pull/92 and released in 2.0.5. I think @tobiasfaust is not using the latest version. I am testing it with `HighPerf.ino` and it works fine.

![image](https://github.com/user-attachments/assets/73126706-1988-42b6-8544-27d3030ce0d9)
![image](https://github.com/user-attachments/assets/48156d56-1805-4879-a501-8cc5090a660a)

**Comment by mathieucarbou** [comment]
For 8266: I saw some issues in the code. HighPerf mode does not compile. I am preparing a PR.

**Comment by mathieucarbou** [comment]
ESP8266 works. Tested on D1 mini
![image](https://github.com/user-attachments/assets/9c2039f5-2053-4764-afef-916d14204826)
![image](https://github.com/user-attachments/assets/a39a2b8b-37cf-4ae5-aa2f-48b38388adbf)

**Comment by tobiasfaust** [comment]
thank you, it works well now with ESP8266
